export const WEBAPPLICATION_API_ENDPOINT = import.meta.env.VITE_WEBAPPLICATION_API_ENDPOINT
export const WEBAPPLICATION_API_URL_EPR = import.meta.env.VITE_WEBAPPLICATION_API_URL_EPR

export const PICKUP_RESULT_PROCESS_CODE = "CBF320500"